# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol_to_server.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protocol_to_server.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18protocol_to_server.proto\"\xf9\x01\n\x11\x42\x43\x43_Dist_toServer\x12?\n\x07\x63ommand\x18\x01 \x02(\x0e\x32&.BCC_Dist_toServer.CommandTypetoServer:\x06\x43MD_ID\x12\x0e\n\x06myname\x18\x02 \x01(\t\x12\x1d\n\treceivers\x18\x03 \x03(\x0b\x32\n.BCC_users\x12\x0f\n\x07message\x18\x04 \x01(\t\"c\n\x13\x43ommandTypetoServer\x12\n\n\x06\x43MD_ID\x10\x00\x12\x0c\n\x08\x43MD_LIST\x10\x01\x12\x0f\n\x0b\x43MD_SENDALL\x10\x02\x12\x0f\n\x0b\x43MD_SENDONE\x10\x03\x12\x10\n\x0c\x43MD_SENDLIST\x10\x04\"\xed\x01\n\x11\x42\x43\x43_Dist_toClient\x12@\n\x07\x63ommand\x18\x01 \x02(\x0e\x32&.BCC_Dist_toClient.CommandTypetoClient:\x07\x43MD_MSG\x12#\n\x07message\x18\x02 \x01(\x0b\x32\x12.BCC_formatMessage\x12\x19\n\x05users\x18\x03 \x03(\x0b\x32\n.BCC_users\x12\x15\n\rerror_message\x18\x04 \x01(\t\"?\n\x13\x43ommandTypetoClient\x12\x0c\n\x08\x43MD_LIST\x10\x00\x12\x0b\n\x07\x43MD_MSG\x10\x01\x12\r\n\tCMD_ERROR\x10\x02\"\x19\n\tBCC_users\x12\x0c\n\x04name\x18\x01 \x02(\t\"Y\n\x11\x42\x43\x43_formatMessage\x12\x10\n\x08receiver\x18\x01 \x02(\t\x12\x0f\n\x07message\x18\x02 \x02(\t\x12\x0e\n\x06source\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03'
)



_BCC_DIST_TOSERVER_COMMANDTYPETOSERVER = _descriptor.EnumDescriptor(
  name='CommandTypetoServer',
  full_name='BCC_Dist_toServer.CommandTypetoServer',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CMD_ID', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CMD_LIST', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CMD_SENDALL', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CMD_SENDONE', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CMD_SENDLIST', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=179,
  serialized_end=278,
)
_sym_db.RegisterEnumDescriptor(_BCC_DIST_TOSERVER_COMMANDTYPETOSERVER)

_BCC_DIST_TOCLIENT_COMMANDTYPETOCLIENT = _descriptor.EnumDescriptor(
  name='CommandTypetoClient',
  full_name='BCC_Dist_toClient.CommandTypetoClient',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CMD_LIST', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CMD_MSG', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CMD_ERROR', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=455,
  serialized_end=518,
)
_sym_db.RegisterEnumDescriptor(_BCC_DIST_TOCLIENT_COMMANDTYPETOCLIENT)


_BCC_DIST_TOSERVER = _descriptor.Descriptor(
  name='BCC_Dist_toServer',
  full_name='BCC_Dist_toServer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='BCC_Dist_toServer.command', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='myname', full_name='BCC_Dist_toServer.myname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='receivers', full_name='BCC_Dist_toServer.receivers', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='BCC_Dist_toServer.message', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BCC_DIST_TOSERVER_COMMANDTYPETOSERVER,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=278,
)


_BCC_DIST_TOCLIENT = _descriptor.Descriptor(
  name='BCC_Dist_toClient',
  full_name='BCC_Dist_toClient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='BCC_Dist_toClient.command', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='BCC_Dist_toClient.message', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='users', full_name='BCC_Dist_toClient.users', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='BCC_Dist_toClient.error_message', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BCC_DIST_TOCLIENT_COMMANDTYPETOCLIENT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=281,
  serialized_end=518,
)


_BCC_USERS = _descriptor.Descriptor(
  name='BCC_users',
  full_name='BCC_users',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='BCC_users.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=520,
  serialized_end=545,
)


_BCC_FORMATMESSAGE = _descriptor.Descriptor(
  name='BCC_formatMessage',
  full_name='BCC_formatMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='receiver', full_name='BCC_formatMessage.receiver', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='BCC_formatMessage.message', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source', full_name='BCC_formatMessage.source', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='BCC_formatMessage.timestamp', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=547,
  serialized_end=636,
)

_BCC_DIST_TOSERVER.fields_by_name['command'].enum_type = _BCC_DIST_TOSERVER_COMMANDTYPETOSERVER
_BCC_DIST_TOSERVER.fields_by_name['receivers'].message_type = _BCC_USERS
_BCC_DIST_TOSERVER_COMMANDTYPETOSERVER.containing_type = _BCC_DIST_TOSERVER
_BCC_DIST_TOCLIENT.fields_by_name['command'].enum_type = _BCC_DIST_TOCLIENT_COMMANDTYPETOCLIENT
_BCC_DIST_TOCLIENT.fields_by_name['message'].message_type = _BCC_FORMATMESSAGE
_BCC_DIST_TOCLIENT.fields_by_name['users'].message_type = _BCC_USERS
_BCC_DIST_TOCLIENT_COMMANDTYPETOCLIENT.containing_type = _BCC_DIST_TOCLIENT
DESCRIPTOR.message_types_by_name['BCC_Dist_toServer'] = _BCC_DIST_TOSERVER
DESCRIPTOR.message_types_by_name['BCC_Dist_toClient'] = _BCC_DIST_TOCLIENT
DESCRIPTOR.message_types_by_name['BCC_users'] = _BCC_USERS
DESCRIPTOR.message_types_by_name['BCC_formatMessage'] = _BCC_FORMATMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BCC_Dist_toServer = _reflection.GeneratedProtocolMessageType('BCC_Dist_toServer', (_message.Message,), {
  'DESCRIPTOR' : _BCC_DIST_TOSERVER,
  '__module__' : 'protocol_to_server_pb2'
  # @@protoc_insertion_point(class_scope:BCC_Dist_toServer)
  })
_sym_db.RegisterMessage(BCC_Dist_toServer)

BCC_Dist_toClient = _reflection.GeneratedProtocolMessageType('BCC_Dist_toClient', (_message.Message,), {
  'DESCRIPTOR' : _BCC_DIST_TOCLIENT,
  '__module__' : 'protocol_to_server_pb2'
  # @@protoc_insertion_point(class_scope:BCC_Dist_toClient)
  })
_sym_db.RegisterMessage(BCC_Dist_toClient)

BCC_users = _reflection.GeneratedProtocolMessageType('BCC_users', (_message.Message,), {
  'DESCRIPTOR' : _BCC_USERS,
  '__module__' : 'protocol_to_server_pb2'
  # @@protoc_insertion_point(class_scope:BCC_users)
  })
_sym_db.RegisterMessage(BCC_users)

BCC_formatMessage = _reflection.GeneratedProtocolMessageType('BCC_formatMessage', (_message.Message,), {
  'DESCRIPTOR' : _BCC_FORMATMESSAGE,
  '__module__' : 'protocol_to_server_pb2'
  # @@protoc_insertion_point(class_scope:BCC_formatMessage)
  })
_sym_db.RegisterMessage(BCC_formatMessage)


# @@protoc_insertion_point(module_scope)
